services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=service_library
      - DB_USER=postgres
      - DB_PASSWORD=admin
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: service_library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/migration:/docker-entrypoint-initdb.d

volumes:
  postgres_data: